#!/bin/bash
# Description: conversion from MS-Word 2007 Open XML to PDF/A-1

if [ -z "$TE_HOME" ]; then
    echo "TE_HOME not defined!"
    exit 1
fi

. "$TE_HOME"/etc/te.conf
. "$TE_HOME"/etc/te.d/env
. "$TE_HOME/test-data/common.sh"

TESTIN="$TE_HOME"/test-data/test.docx
TESTOUT=`mktemp_out test.docx .pdfa`

echo
echo "* Checking conversion from MS-Word 2007 Open XML to PDF/A-1..."
"$TE_HOME"/lib/engines/ooo2pdfa "$TESTIN" "$TESTOUT"
RET=$?
if [ $RET -ne 0 ]; then
    echo "Engine exited with error code '$RET'!"
    exit $RET
fi
SIZE=`stat -c %s "$TESTOUT" 2> /dev/null`

if [ ! -f "$TESTOUT" -o "$SIZE" = "0" ]; then
    echo "  Error: conversion of '$TESTIN' to '$TESTOUT' failed!"
    exit 1
fi

grep "\/GTS_PDFA1\>" "$TESTOUT" 1> /dev/null 2>&1
RET=$?
if [ $RET -ne 0 ]; then
    echo "  Warning: '$TESTOUT' ($SIZE bytes) does not seems to be a PDF/A-1 file!"
    exit 1
fi
echo "  Ok: '$TESTOUT' ($SIZE bytes)"
exit 0
