#!/bin/bash
# Description: conversion from ODT to PDF

if [ -z "$TE_HOME" ]; then
    echo "TE_HOME not defined!"
    exit 1
fi

. "$TE_HOME"/etc/te.conf
. "$TE_HOME"/etc/te.d/env
. "$TE_HOME/test-data/common.sh"

if [ -n "$REQUEST_DIRECTORY" ]; then
    export TMPDIR=$REQUEST_DIRECTORY
fi

TESTIN="$TE_HOME"/test-data/test.odt
TESTOUT=`mktemp_out test.odt .pdf`

echo
echo "* Checking conversion from ODT to PDF..."
"$TE_HOME"/lib/engines/ooo2pdf "$TESTIN" "$TESTOUT"
SIZE=`stat -c %s "$TESTOUT" 2> /dev/null`

if [ ! -f "$TESTOUT" -o "$SIZE" = "0" ]; then
    echo "  Error: Conversion of '$TESTIN' to '$TESTOUT' failed!"
    exit 1
fi
echo "  Ok: '$TESTOUT' ($SIZE bytes)"
exit 0
