#!/bin/bash
# Description: conversion from ZIP to ODT

if [ -z "$TE_HOME" ]; then
    echo "TE_HOME not defined!"
    exit 1
fi

. "$TE_HOME"/etc/te.conf
. "$TE_HOME"/etc/te.d/env
. "$TE_HOME/test-data/common.sh"

TESTIN="$TE_HOME"/test-data/test.zip
TESTOUT=`mktemp_out test.mergeodt.zip .odt`

echo 
echo "* Checking conversion from ZIP to ODT..."
"$TE_HOME"/lib/engines/zip2star odt "$TESTIN" "$TESTOUT"
RET=$?
if [ $RET -ne 0 ]; then
    echo "Engine exited with error code '$RET'!"
    exit $RET
fi
SIZE=`stat -c %s "$TESTOUT" 2> /dev/null`

if [ ! -f "$TESTOUT" -o "$SIZE" = "0" ]; then
    echo "Error: conversion of '$TESTIN' to '$TESTOUT' failed!"
    exit 1
fi
echo "  Ok: '$TESTOUT' ($SIZE bytes)"
exit 0
