#!/bin/bash

if [ -z "$TE_HOME" ]; then
    MY_PATH=$0
    if [ -L "$MY_PATH" ]; then
        MY_PATH=`readlink "$MY_PATH"`
    fi
    DIRNAME=`dirname "$MY_PATH"`
    DIRNAME="$DIRNAME/../../"
    REAL_DIRNAME=`cd "$DIRNAME" 1 > /dev/null 2>&1 && pwd`
    export TE_HOME=$REAL_DIRNAME
fi

BEAGLE_DOC_EXTRACTOR=beagle-doc-extractor
BEAGLE_LC_ALL=$LANG

[ -f "$TE_HOME"/etc/te.conf ] && . "$TE_HOME"/etc/te.conf
[ -f "$TE_HOME"/etc/te.d/env ] && . "$TE_HOME"/etc/te.d/env

function usage {
    echo "Usage: $0 <input_file.doc> <output_file.txt>"
    exit 1
}

if [ -z "$1" ] || [ -z "$2" ]; then
    usage
fi

OUT=`mktemp -t beagledoc2txt.XXXXXX`
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error creating temp file!"
    exit $RET
fi

LC_ALL="$BEAGLE_LC_ALL" "$BEAGLE_DOC_EXTRACTOR" "$1" > "$OUT"
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error running '$BEAGLE_DOC_EXTRACTOR $1'!"
    exit $RET
fi

perl -ne 's/\*\*(HOT|BREAK)\*\*//g;print' < "$OUT" > "$2"
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error extracting content from '$OUT'!"
    exit $RET
fi

rm -f "$OUT"

exit 0