#!/bin/bash

if [ -z "$TE_HOME" ]; then
    MY_PATH=$0
    if [ -L "$MY_PATH" ]; then
        MY_PATH=`readlink "$MY_PATH"`
    fi
    DIRNAME=`dirname "$MY_PATH"`
    DIRNAME="$DIRNAME/../../"
    REAL_DIRNAME=`cd "$DIRNAME" 1 > /dev/null 2>&1 && pwd`
    export TE_HOME=$REAL_DIRNAME
fi

[ -f "$TE_HOME"/etc/te.conf ] && . "$TE_HOME"/etc/te.conf
[ -f "$TE_HOME"/etc/te.d/env ] && . "$TE_HOME"/etc/te.d/env

function usage {
    echo "Usage: $0 <input_file.ext> <output_file.txt>"
    exit 1
}

if [ -z "${TE_TIKA_SERVER_HOST}" ]; then
    echo "Undefined or missing TE_TIKA_SERVER_HOST environment variable: check your '$TE_HOME/etc/te.conf' file."
    exit 1
fi
if [ -z "${TE_TIKA_SERVER_PORT}" ]; then
    echo "Undefined or missing TE_TIKA_SERVER_PORT environment variable: check your '$TE_HOME/etc/te.conf' file."
    exit 1
fi

if [ -z "$1" ] || [ -z "$2" ]; then
    usage
fi

"$TE_HOME/lib/engines/tika-server-put" "http://${TE_TIKA_SERVER_HOST}:${TE_TIKA_SERVER_PORT}/tika" "$1" "$2"
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error running '$TE_HOME/lib/engines/tika-server-put' 'http://${TE_TIKA_SERVER_HOST}:${TE_TIKA_SERVER_PORT}/tika' '$1' '$2'"
    exit $RET
fi

exit 0
